FROM debian:trixie

RUN apt update && \
    apt install -y python3 python3-pip && \
    apt clean && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY . /app

RUN pip3 install --break-system-packages -r requirements.txt

RUN chmod +x ./init_python.sh

CMD [ "./init_python.sh" ]

EXPOSE 8888

ENTRYPOINT [ "python3", "main.py" ]